export const centres = [
  {
    slug: "saint-doulchard",
    name: "Saint-Doulchard",
    entity: "INOV",
    logo: "/images/logo-centre-inov.png",
    logoAlt: "Logo du centre INOV",
    website: "https://www.inov-medecine-nucleaire.com/",
    websiteDisplay: "inov-medecine-nucleaire.com",
    websiteReady: true,
    speciality: "Scintigraphie et cardiologie nucléaire",
    type: "Centre de médecine nucléaire",
    address: ["Hôpital Privé Guillaume de Varye", "210 route de Vouzeron", "18230 Saint-Doulchard"],
    phone: "02 48 23 99 60",
    phoneHref: "+33248239960",
    email: "inov.rdv@gmail.com",
    access: "Parking patients par l’entrée 1, route de Vouzeron. Le service est accessible aux personnes à mobilité réduite.",
    hours: "Secrétariat téléphonique du lundi au vendredi, de 8 h à 12 h et de 14 h à 17 h.",
    description: "Au sein de l’Hôpital Privé Guillaume de Varye, le centre INOV accueille les patients pour les examens de scintigraphie et de cardiologie nucléaire.",
    image: "/images/centre_saint-doulchard.jpg",
    imageAlt: "Entrée du service de scintigraphie INOV à Saint-Doulchard",
    imageCaption: "Entrée du centre de Saint-Doulchard",
    mapQuery: "INOV scintigraphie 210 route de Vouzeron 18230 Saint-Doulchard",
    note: "Les examens TEP sont réalisés sur le site CHERMED à Bourges.",
  },
  {
    slug: "bourges",
    name: "Bourges",
    entity: "CHERMED",
    logo: "/images/logo-centre-chermed.jpeg",
    logoAlt: "Logo CHERMED, unité TEP Scanner du site Jacques Cœur",
    website: "https://chermed.fr/",
    websiteDisplay: "chermed.fr",
    websiteReady: false,
    speciality: "TEP Scanner",
    type: "Unité dédiée à l’imagerie TEP",
    address: ["Unité TEP du site Jacques Cœur", "181 avenue François Mitterrand", "18000 Bourges"],
    phone: "02 46 96 86 56",
    phoneHref: "+33246968656",
    email: "secretariat@chermed.fr",
    access: "Le centre se situe sur le site Jacques Cœur à Bourges. Votre convocation précise les modalités d’accueil pour votre examen.",
    hours: null,
    description: "CHERMED est la structure dédiée aux examens TEP Scanner à Bourges, créée par les médecins d’INOV en lien avec les équipes médicales du groupe.",
    image: "/images/scanner.jpg",
    imageAlt: "Exemple d’équipement TEP Scanner",
    imageCaption: "Illustration d’un équipement TEP Scanner",
    mapQuery: "CHERMED unité TEP site Jacques Cœur 181 avenue François Mitterrand 18000 Bourges",
    note: "Pour une scintigraphie, rendez-vous au centre INOV de Saint-Doulchard.",
  },
  {
    slug: "nevers",
    name: "Nevers",
    entity: "CM2N",
    logo: "/images/logo-centre-cm2n.jpg",
    logoAlt: "Logo du Centre de Médecine Nucléaire de la Nièvre",
    website: "https://mednuc58.fr/",
    websiteDisplay: "mednuc58.fr",
    websiteReady: false,
    speciality: "Médecine nucléaire",
    type: "Centre de Médecine Nucléaire de la Nièvre",
    address: ["Hôpital Pierre Bérégovoy", "1 avenue Patrick Guillot", "58000 Nevers"],
    phone: "03 86 93 70 00",
    phoneHref: "+33386937000",
    phoneNote: "Standard de l’hôpital",
    email: "secretariat@mednuc58.fr",
    access: "Le service est situé sur le site de l’Hôpital Pierre Bérégovoy. Confirmez votre lieu de rendez-vous sur votre convocation.",
    hours: null,
    description: "Le Centre de Médecine Nucléaire de la Nièvre accompagne le parcours d’imagerie sur le territoire nivernais, en coopération avec l’Hôpital Pierre Bérégovoy.",
    image: "/images/scanner3.jpg",
    imageAlt: "Exemple d’équipement de médecine nucléaire",
    imageCaption: "Illustration de l’activité de médecine nucléaire",
    mapQuery: "Hôpital Pierre Bérégovoy 1 avenue Patrick Guillot 58000 Nevers",
    note: "Le numéro affiché est celui du standard hospitalier. Pour joindre directement le secrétariat du centre, utilisez l’adresse e-mail ci-dessus.",
  },
];

export const centreBySlug = (slug) => centres.find((centre) => centre.slug === slug);
export const mapHref = (centre) => `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(centre.mapQuery)}`;
